# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TeamSomeName
url: http://teamsomename.com
email: your-email@domain.com
description: Team Some Name is a collection of something something things we love something food reviews and photography something
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
gems: [jekyll-paginate]
paginate: 8
paginate_path: "page/:num"
permalink: /:title
post_dirs: false
categories: food, photography, thoughts

# Build settings
markdown: kramdown

